stages:
  - github-sync
  - build_and_test
  - build_packages
  - release

variables:
    PYENV_PYTHON_VERSION: 3.5.5

image: registry.duniter.org/cebash/duniterpy-builder:0.0.9

before_script:
  - sudo apt update; sudo apt install -y zip

push_to_github:
  stage: github-sync
  variables:
    GIT_STRATEGY: none
  tags:
    - github
  script:
    - rm -rf ./*
    - rm -rf .git
    - git clone --mirror $CI_REPOSITORY_URL .
    - git remote add github $GITHUB_URL_AND_KEY
    - git config --global user.email "contact@duniter.org"
    - git config --global user.name "Duniter"
    # Job would fail if we don't remove refs about pull requests
    - bash -c "cat packed-refs | grep -v 'refs/pull' > packed-refs-new; echo 'Removed pull refs.'"
    - mv packed-refs-new packed-refs
    - bash -c "git push --force --mirror github 2>&1 | grep -v duniter-gitlab; echo $?"

.env: &env
  tags:
    - redshift-docker-python
  before_script:
    - export PYENV_ROOT="$HOME/.pyenv"
    - export PATH="$PYENV_ROOT/bin:$PATH"
    - eval "$(pyenv init -)"
    - pyenv shell $PYENV_PYTHON_VERSION
    - export PATH=/opt/qt/5.9/5.9.4/gcc_64/bin:$PATH
    - export DISPLAY=:99


build_and_test: &build_and_test
  <<: *env
  stage: build_and_test
  when: always
  script:
    - pip install wheel
    - pip install pytest-cov
    - pip install -r requirements.txt
    - python gen_resources.py
    - python gen_translations.py --lrelease
    - python setup.py bdist_wheel
    - py.test --cov=sakia tests/

build_packages:
  <<: *env
  stage: build_packages
  script:
    - docker/build_dependencies.sh
    - docker/build.sh
    - docker/build_package.sh
  artifacts:
    paths:
    - /builds/*

releases:
  <<: *env
  stage: release
  when: manual
  script:
    - pip install -r requirements.txt
    - pip install wheel
    - pip install twine
    - python setup.py bdist_wheel
    - twine upload dist/* --username duniter --password $PYPI_PASSWORD
